#!/usr/bin/env bash
# Generated by fargate-to-cloudrun. Read every step before running it.
# Every step is self-contained (its own --project and --region, no shared variables), so the agent
# can run them one at a time in separate shells. The file also runs top to bottom; the PAUSE step's
# `read` exists for that whole-file run.
set -euo pipefail

# ---- Step 1: Enable the Cloud Run, Artifact Registry and Secret Manager APIs
# Google Cloud switches services on per project; nothing below works until these are enabled. Enabling is free.
# Docs: https://docs.cloud.google.com/run/docs/setup
gcloud services enable run.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com --project=my-project

# ---- Step 2: Create the runtime service account if it does not exist
# Every Cloud Run service runs as a Google service account, its identity when calling Google APIs. It carries no AWS credentials.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/service-identity
gcloud iam service-accounts describe web-run@my-project.iam.gserviceaccount.com --project=my-project >/dev/null 2>&1 || gcloud iam service-accounts create web-run --display-name='web on Cloud Run' --project=my-project

# ---- Step 3: Create each Secret Manager secret (empty) if it does not exist
# Secret Manager replaces AWS Secrets Manager and SSM. Values are added by you in a later step, never by this script.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/secrets
for s in prod-db-url; do gcloud secrets describe "$s" --project=my-project >/dev/null 2>&1 || gcloud secrets create "$s" --replication-policy=automatic --project=my-project; done

# ---- Step 4: Grant the runtime service account access to each secret
# The docs: to allow Cloud Run to access the secret, the service identity must have the Secret Manager Secret Accessor role.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/secrets
for s in prod-db-url; do gcloud secrets add-iam-policy-binding "$s" --member=serviceAccount:web-run@my-project.iam.gserviceaccount.com --role=roles/secretmanager.secretAccessor --project=my-project >/dev/null; done

# ---- Step 5: PAUSE: add a value to every secret yourself, then continue
# The manifest pins each secret to version 1. In another terminal run each command below, type the value, then press Ctrl-D. This script never sees the values.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/secrets
echo "  gcloud secrets versions add prod-db-url --data-file=- --project=my-project"
read -r -p "Press Enter once every secret above has a version... "

# ---- Step 6: Deploy the service from service.yaml
# gcloud run services replace applies the manifest; the first run creates the service, later runs create a new revision.
# Docs: https://docs.cloud.google.com/run/docs/deploying
gcloud run services replace out/service.yaml --region=us-central1 --project=my-project

# ---- Step 7: Fetch the service URL
# Every Cloud Run service gets a stable HTTPS URL on run.app.
# Docs: https://docs.cloud.google.com/run/docs/deploying
gcloud run services describe web --region=us-central1 --project=my-project --format='value(status.url)'

# ---- Step 8: Smoke test with your own identity token (the service stays private)
# Callers need the Cloud Run Invoker role; as project owner you already have it. No public access is granted here.
# Docs: https://docs.cloud.google.com/run/docs/authenticating/developers
curl -sf --retry 5 --retry-delay 3 -H "Authorization: Bearer $(gcloud auth print-identity-token)" "$(gcloud run services describe web --region=us-central1 --project=my-project --format='value(status.url)')"/ >/dev/null && echo "SMOKE OK" || { echo "SMOKE FAILED"; exit 1; }

# ---- Step 9: Show the last 20 log lines
# Cloud Run captures stdout and stderr as logs automatically; no agent to install.
# Docs: https://docs.cloud.google.com/run/docs/logging
gcloud run services logs read web --region=us-central1 --project=my-project --limit=20
