#!/usr/bin/env bash
# Generated by fargate-to-cloudrun. Read every step before running it.
# Every step is self-contained (its own --project and --region, no shared variables), so the agent
# can run them one at a time. Use set -euo pipefail in each shell; review the project and existing service first.
set -euo pipefail

# ---- Step 1: Enable the Cloud Run, Artifact Registry and Secret Manager APIs
# Google Cloud switches services on per project; nothing below works until these are enabled. Enabling is free.
# Docs: https://docs.cloud.google.com/run/docs/setup
gcloud services enable run.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com --project=my-project

# ---- Step 2: Create the runtime service account if it does not exist
# Every Cloud Run service runs as a Google service account, its identity when calling Google APIs. It carries no AWS credentials.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/service-identity
gcloud iam service-accounts describe web-run@my-project.iam.gserviceaccount.com --project=my-project >/dev/null 2>&1 || gcloud iam service-accounts create web-run --display-name='web on Cloud Run' --project=my-project

# ---- Step 3: Grant the runtime service account access to each secret
# The docs: to allow Cloud Run to access the secret, the service identity must have the Secret Manager Secret Accessor role.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/secrets
for s in prod-db-url; do gcloud secrets add-iam-policy-binding "$s" --member=serviceAccount:web-run@my-project.iam.gserviceaccount.com --role=roles/secretmanager.secretAccessor --project=my-project >/dev/null; done

# ---- Step 4: Verify every pinned secret version is enabled
# Import the approved secrets before deployment, then regenerate with --secret-versions. This check reads metadata only.
# Docs: https://docs.cloud.google.com/run/docs/configuring/services/secrets
test "$(gcloud secrets versions describe 1 --secret=prod-db-url --project=my-project --format='value(state)')" = ENABLED

# ---- Step 5: Deploy the service from service.yaml
# gcloud run services replace applies the manifest; the first run creates the service, later runs create a new revision.
# Docs: https://docs.cloud.google.com/run/docs/deploying
gcloud run services replace out/service.yaml --region=us-central1 --project=my-project

# ---- Step 6: Fetch the service URL
# Every Cloud Run service gets a stable HTTPS URL on run.app.
# Docs: https://docs.cloud.google.com/run/docs/deploying
gcloud run services describe web --region=us-central1 --project=my-project --format='value(status.url)'

# ---- Step 7: Smoke test the run.app URL with your own identity token
# The caller needs Cloud Run Invoker. Reaching run.app directly only works while ingress is all; it checks HTTP reachability only, so run application tests before cutover.
# Docs: https://docs.cloud.google.com/run/docs/authenticating/developers
curl -sf --retry 5 --retry-delay 3 -H "Authorization: Bearer $(gcloud auth print-identity-token)" "$(gcloud run services describe web --region=us-central1 --project=my-project --format='value(status.url)')"/ >/dev/null && echo "SMOKE OK" || { echo "SMOKE FAILED"; exit 1; }

# ---- Step 8: Show the last 20 log lines
# Cloud Run captures stdout and stderr as logs automatically; no agent to install.
# Docs: https://docs.cloud.google.com/run/docs/logging
gcloud run services logs read web --region=us-central1 --project=my-project --limit=20
